services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: /usr/src/app/entrypoint.sh
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
    # 로컬 개발 시 소스 코드 변경을 즉시 반영하기 위한 볼륨 설정
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql-data: