FROM node:20-slim
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    python3 \
    make \
    g++ \
    libcairo2-dev \
    libjpeg-dev \
    libpango1.0-dev \
    libgif-dev \
    ghostscript \
    poppler-utils \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

# CMD 명령어는 docker-compose.yml에서 덮어쓰므로 여기서는 제거