import type { Metadata } from "next";                // Next.js에서 제공하는 메타데이터 타입 import
import "./globals.css";                              // 전역 CSS import

// 메타데이터 설정
export const metadata: Metadata = {
  title: "Create Next App",                         // 페이지 타이틀
  description: "Generated by create next app",     // 페이지 설명
};

// RootLayout 컴포넌트 - 모든 페이지에 공통으로 적용되는 레이아웃
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;                        // 하위 페이지 컴포넌트들이 children으로 들어옴
}>) {
  return (
    <html lang="en">
      {/* Geist Sans 폰트 클래스가 body에 적용됩니다 */}
      <body>
        {/* 이 children이 page.tsx로 교체됩니다! */}
        {children}
      </body>
    </html>
  );
}
