name: Deploy with Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ toLower(github.repository) }}:latest
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 기존 컨테이너 중지 및 삭제
            if [ "$(docker ps -q -f name=pdf-app-server)" ]; then
              docker stop pdf-app-server
              docker rm pdf-app-server
            fi

            # 최신 이미지 pull 및 새 컨테이너 실행
            docker pull ghcr.io/${{ toLower(github.repository) }}:latest
            docker run -d --name pdf-app-server -p 3000:3000 ghcr.io/${{ toLower(github.repository) }}:latest